---
__default__:
    "nCPUs"     : "16"
    "mem"    : 20000
    # "queue": "analysis"
#    "resources" : "\"select[mem>20000] rusage[mem=20000] span[hosts=1]\""
    "name"      : "JOBNAME.{rule}.{wildcards}"
    # "output"    : "log/{rule}.PBS_JOBID.out"
    # "error"     : "log/{rule}.PBS_JOBID.err"
    "time"      : "01:00:00:00"


##########################
######  ALIGN RULES ######
#########################

indexBam:
  time: "07:00:00"
  nCPUs: "4"
  mem: 10G
#<*><*><*><*><*><*><*><*><*>


######################
###### SV RULES ######
#####################

Sniffles2:
  time: "10:00:00"
  nCPUs: "11"
  mem: 10G
#<*><*><*><*><*><*><*><*><*>


#########################
######  SNPs RULES ######
#########################
Clair3:
  time: "72:00:00"
  nCPUs: "16"
  mem: 30G
  host: "host=c86q-23+1:host=c86q-22+1:host=c86q-21+1:host=c86q-20+1:host=c86q-19+1:host=c86q-18+1:host=c86q-17+1:host=c86q-16+1:host=c86q-15+1:host=c86q-14+1:host=c86q-13+1:host=c86q-12+1:host=c86q-11"
#<*><*><*><*><*><*><*><*><*>


###############################
######  Benchmark RULES #######
###############################
SNVsBenchmark:
  time: "00:30:00"
  nCPUs: "5"
  mem: 16G
#<*><*><*><*><*><*><*><*><*>


############################
######  PHASNIG RULES ######
###########################

#<*><*><*><*><*><*><*><*><*>


###############################
######  STATISTICS RULES ######
###############################
Mosdepth:
  nCPUs: "10"
  mem: 20G
  time: "10:00:00"

UpdateSNVsStatWithBenchmark:
    time: "72:00:00"
    nCPUs: "16"
    mem: 30G

readsStat:
  nCPUs: "8"
  mem: 20G
  time: "05:00:00:00"

bamStatstics:
  time: "01:00:00:00"
  nCPUs: "4"
  mem: 10G

svStat:
  time: "01:00:00:00"
  nCPUs: "4"
  mem: 10G

snpStat:
  time: "01:00:00:00"
  nCPUs: "4"
  mem: 10G

stat:
  time: "00:00:10:00"
  nCPUs: "1"
  mem: 1G
#<*><*><*><*><*><*><*><*><*>
...
